# Generated by Django 4.2.4 on 2023-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=265, verbose_name='Полное имя')),
                ('phone_number', models.CharField(max_length=265, verbose_name='Номер телефона')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='Пол')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ('-id',),
            },
        ),
    ]
