# Generated by Django 4.2.4 on 2023-08-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-id',), 'verbose_name': 'Приём', 'verbose_name_plural': 'Приемы'},
        ),
    ]
