# Generated by Django 4.2.4 on 2023-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctor_images/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=265, verbose_name='Полное имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('job', models.CharField(max_length=265, verbose_name='Работа')),
                ('phone_number', models.CharField(max_length=265, verbose_name='Номер телефона')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'ordering': ('-id',),
            },
        ),
    ]
