# Generated by Django 4.2.4 on 2023-08-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_award'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
