# Generated by Django 4.2.4 on 2023-08-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctoraward'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265, verbose_name='Название')),
                ('image', models.ImageField(upload_to='hospital_awards_imeges/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Награда больницы',
                'verbose_name_plural': 'Награды больницы',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='doctoraward',
            options={'ordering': ('-id',), 'verbose_name': 'Награда', 'verbose_name_plural': 'Награды'},
        ),
    ]
