# Generated by Django 4.2.4 on 2023-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_hospitalaward_alter_doctoraward_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='job',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='Номер телефона'),
        ),
    ]
